<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Modules/Sync/Nexali.Modules.Sync/Nexali.Modules.Sync.csproj" />
    <ProjectReference Include="../../src/Libraries/Nexali.Client.Sync/Nexali.Client.Sync.csproj" />
    <ProjectReference Include="../../src/Libraries/Nexali.Sync.Protocol/Nexali.Sync.Protocol.csproj" />
  </ItemGroup>

</Project>
