<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Server/Nexali.Api/Nexali.Api.csproj" />
    <ProjectReference Include="../../src/Clients/Web/Nexali.Web/Nexali.Web.csproj" />
  </ItemGroup>

</Project>
